on:
  push:
    branches: [main]

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build
        run: ./scripts/buildprod.sh

      - name: GCloud
        uses: google-github-actions/setup-gcloud@v3

      - name: Push GCloud
        run: gcloud builds submit --tag us-central1-docker.pkg.dev/notely-492423/notely-ar-repo
        
